### PR TITLE
Added features

### PR DESCRIPTION
**Pull request by jvdmr**
* support for Apache 2.4
* support per-virtualhost configuration
* configurable HTTP response status (default remains 403)
* added ready-to-install Debian package for Apache 2.4

### CODE REVIEW

**Comment by SteffenAL** [comment]
Do you plan to make Windows compatible ?

Gregg has ported to Windows and Apache 2.4 compatibility:  [mod_evasive2.c.txt](https://github.com/jzdziarski/mod_evasive/files/1372111/mod_evasive2.c.txt)

**Comment by jvdmr** [comment]
Sure, I've merged my version with his into mod_evasive24win.c

Unfortunately I don't actually have a windows environment to build/test this on, so it's provided as-is. Any bug reports, patches and other tips are of course welcome!

**Comment by SteffenAL** [comment]
Did not build : mod_evasive24win.c(245): error C2065: 's': undeclared identifier

Copied from Greggs one:

```
@@ -242,7 +242,11 @@
             char evasive_timestamp[APR_CTIME_LEN];
 
             snprintf(filename, sizeof(filename), "%s/dos-%s", cfg->log_dir != NULL ? cfg->log_dir : DEFAULT_LOG_DIR, r->useragent_ip);
-            if (stat(filename, &s)) {
+
+#ifndef _WIN32 /* stat won't work in Windows unless file actually exists first */
+        if (stat(filename, &s)) {
+#endif
+
             file = fopen(filename, "w");
             if (file != NULL) {
                 apr_ctime(evasive_timestamp, apr_time_now());
```
Then it builds 

Two warnings:
mod_evasive24win.c(384): warning C4018: '<': signed/unsigned mismatch
mod_evasive24win.c(332) : warning C4716: 'destroy_config': must return a value

**Comment by SteffenAL** [comment]
No warning on Windows anymore

First I got:  Can't locate API module structure **`evasive2_module**'  it is now **evasive_module**

Initial test looks good sofar.

Only seems that IPV6 is not logged, it is blocked.

**Comment by jvdmr** [comment]
Thanks, the `stat(...)` line should not have been there in the first place (I intended to remove it but forgot). I've also fixed the warnings as you noticed.

I will look into IPv6 logging but can't promise when it'll be fixed, see https://github.com/jvdmr/mod_evasive/issues/1

**Comment by Schamschula** [comment]
Any time line for a new release? I marked the MacPorts obsolete, since the old version did not build against apache 2.2.x or 2.4.x.

**Comment by jvdmr** [comment]
I have no control over the release management of this repository. I'm just someone who needed this module with some extra features, so in the spirit of open source I forked the code, implemented what I needed and am now trying to push my changes back to the original repository.

@jzdziarski, please let us know (soonish) if you're still maintaining this, and whether or not you'll accept my pull request (or what you need in order to accept it).

If this module is no longer actively maintained while active maintenance is still wanted (seems like it would be), I'm willing to become the new maintainer and point everyone to my fork as the new official source. But I'd like to wait a while longer, I don't want to take over someone's project while they may be temporarily unable to respond.

**Comment by virgme** [comment]
how to install in vps ?

**Comment by jvdmr** [comment]
@virgme You will have to be more specific. A VPS is just a server like any other, as far as this piece of software is concerned. Check which version of Apache you're running, then follow the instructions for that version. If this does not work for you, please give us more details so we can help more accurately.

**Comment by q2dg** [comment]
@jzdziarski Could you say something about this, please? Thanks a lot!

**Comment by jeensg** [comment]
Does anybody have contact with @jzdziarski ? Do have some questions but mailaddress shown in readme isn't working.
@jvdmr do you still think about forking it officially, since it's now been a while with no answer!?

**Comment by ROBERT-MCDOWELL** [comment]
maybe create a new git as a mirror and reference to this git would be wise

**Comment by jvdmr** [comment]
It's been over a year since I created this PR, I suppose it's fair to say this repo is no longer maintained by now. Feel free to use my fork (https://github.com/jvdmr/mod_evasive) as the official new version, log your issues on it, etc.

To me this is something I work on in my free time (of which I don't have much), that I happen to use in production as well, so I can't promise fast delivery of bugfixes or features, but if anyone wants to submit fixes of their own I'll gladly check and merge them.

**Comment by ROBERT-MCDOWELL** [comment]
done thanks!

**Pull request closed without merging**
